version: "3"
services:
  warehouse-app:
    build: warehouse-app
    ports:
      - ${WAREHOUSE_APP_API_PORT}:${WAREHOUSE_APP_API_PORT}
    environment:
      - API_PORT=${WAREHOUSE_APP_API_PORT}
      - DB_HOST=mongodb
      - DB_NAME=${WAREHOUSE_DB_NAME}
#      - DB_USERNAME=${WAREHOUSE_DB_ROOT_USERNAME}
#      - DB_PASSWORD=${WAREHOUSE_DB_ROOT_PASSWORD}
      - TEST_DB_HOST=${WAREHOUSE_DB_HOST}
      - TEST_DB_NAME=${WAREHOUSE_DB_NAME}
#      - TEST_DB_USERNAME=${WAREHOUSE_DB_ROOT_USERNAME}
#      - TEST_DB_PASSWORD=${WAREHOUSE_DB_ROOT_USERNAME}
      - LOGISTICS_APP_HOST=logistics
      - LOGISTICS_APP_PORT=8080
    depends_on:
      - mongodb


  payments-app:
    build: payments-app
    ports:
      - 5000:5000
    environment:
      - DB_HOST=payments-db
      - DB_NAME=${PAYMENTS_DB_NAME}
      - DB_USERNAME=${PAYMENTS_DB_USERNAME}
      - DB_PASSWORD=${PAYMENTS_DB_PASSWORD}
      - WAREHOUSE_HOST=warehouse-app
      - WAREHOUSE_PORT=${WAREHOUSE_APP_API_PORT}
    depends_on:
      - payments-db
      - warehouse-app


  logistics:
    restart: on-failure
    image: goodforgod/logistics
    env_file:
      - .env
    ports:
      - "8080:8080"
    links:
      - mongodb
    environment:
      - MONGO_DB=logistics
      - MONGO_URI=mongodb:27017
      #      - MONGO_URI=user:pass@mongodb:27017
      - ADVERTISE_HOST=advertising
    depends_on:
      - mongodb


  advertising:
    restart: on-failure
    image: goodforgod/advertising
    env_file:
      - .env
    ports:
      - "8081:8081"
    links:
      - mongodb
    environment:
      - MONGO_DB=advertising
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASS=
    depends_on:
      - mongodb


  mongodb:
    restart: on-failure
    build: warehouse-db
    env_file:
      - .env
    ports:
      - 27017:27017
    #    volumes:
    #      - ./warehouse-db/db:/data/db
    environment:
      - DB_NAME=${WAREHOUSE_DB_NAME}
      - DB_USERNAME=${WAREHOUSE_DB_USERNAME}
      - DB_PASSWORD=${WAREHOUSE_DB_PASSWORD}


  payments-db:
    build: payments-db
    ports:
      - 5432:5432
    #    volumes:
    #      - ./payments-db/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PAYMENTS_DB_USERNAME}
      - POSTGRES_PASSWORD=${PAYMENTS_DB_PASSWORD}
      - POSTGRES_DB=${PAYMENTS_DB_NAME}
